---
title: "EDA"
author: "Xue Zhang"
date: "2023-10-05"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

Example

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"),
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id,
      USW00094728 = "CentralPark_NY",
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Weatherhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
select(name, id, everything())
```


Initial numeric explorations

```{r}
weather_df |>
  ggplot(aes(x = prcp)) +
  geom_histogram()
```


```{r}
weather_df |>
  filter(prcp >= 1000)
```

```{r}
weather_df |>
  filter(tmax >= 20, tmax <= 30) |>
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point(alpha = .75)
```


`group_by`

```{r}
weather_df |>
  group_by(name, month)
```

Counting things

```{r}
weather_df |>
  group_by(month) |>
  summarize(n_obs = n())
```


```{r}
weather_df |>
  group_by(name, month) |>
  summarize(n_obs = n())
```


```{r}
weather_df |>
  count(month, name = "n_obs")
```


```{r}
weather_df |>
  group_by(month) |>
  summarize(
    n_obs = n(),
    n_days = n_distinct(date)
  )
```


(2 by 2 tables)


```{r}
weather_df |>
  mutate(
    cold = case_when(
      tmax < 5  ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
    )
  ) |>
  filter(name != "Waikiki_HA") |>
  group_by(name, cold) |>
  summarize(count = n())
```


```{r}
weather_df |>
  mutate(cold = case_when(
    tmax <  5 ~ "cold",
    tmax >= 5 ~ "not_cold",
    TRUE      ~ ""
  ))|>
  filter(name != "Waikiki_HA") |>
  janitor::tabyl(name, cold)
```


General summaries

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    mean_tmax = mean(tmax),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax),
    sd_tmax = sd(tmax)
  )
```


```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax),
    median_tmax = median(tmax)
  )
```


```{r}
weather_df |>
  group_by(name, month) |>
  summarize(across(tmin:prcp, mean ))
```


```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax)) |>
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
    geom_point() + geom_line() +
    theme(legend.position = "bottom")
  
```


```{r}
weather_df |>
  group_by(name, month) |>
  summarize(mean_tmax = mean(tmax)) |>
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) |>
  knitr::kable(digits = 1)
```


Grouped mutate

```{r}
weather_df |>
  group_by(name) |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) |>
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
    geom_point()
```



Window functions


```{r}
weather_df |>
  group_by(name, month) |>
  mutate(temp_ranking = min_rank(tmax))
```



```{r}
weather_df |>
  group_by(name, month) |>
  filter(min_rank(tmax) < 2)
```


```{r}
weather_df |>
  group_by(name, month) |>
  filter(min_rank(desc(tmax)) < 4)
```



```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax))
```



```{r}
weather_df |>
  group_by(name) |>
  mutate(temp_change = tmax - lag(tmax)) |>
  summarize(
    temp_change_sd = sd(temp_change, na.rm = TRUE),
    temp_change_max = max(temp_change, na.rm = TRUE)
  )
```



Limitations


